# Generated by Django 6.0.1 on 2026-01-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('temperature', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('real_feel', models.IntegerField(blank=True, null=True)),
                ('wind_direction', models.CharField(blank=True, max_length=50, null=True)),
                ('sunrise', models.CharField(blank=True, max_length=50, null=True)),
                ('is_daytime', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
